### ISSUE TITLE
Icon is not displayed

### ISSUE THREAD

**Issue by ZubAnt** [silentsokolov/django-admin-rangefilter#21] opened 2018-10-29 15:02 UTC
## calendar icon is not displayed in admin panel for DateRangeFilter and DateTimeRangeFilter

django==2.1.2
django-admin-rangefilter==0.3.8
<img width="244" alt="2018-10-29 18 05 24" src="https://user-images.githubusercontent.com/19777376/47659097-3b8d4180-dba5-11e8-95d6-14285ca36606.png">

**Comment by ZubAnt** [comment] 2018-10-30 08:38
i compared  html on "edit page" and on filter

### edit page
<img width="707" alt="2018-10-30 11 24 57" src="https://user-images.githubusercontent.com/19777376/47705323-45f81b80-dc37-11e8-930b-593d67702748.png">

### filter
<img width="872" alt="2018-10-30 11 29 07" src="https://user-images.githubusercontent.com/19777376/47705329-4d1f2980-dc37-11e8-8ec3-b9250f244151.png">

**Comment by silentsokolov** [comment] 2018-10-30 08:45
I could not reproduce the error. The [following code](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/filter.py#L119) probably does not work correctly. You are using Admin/Form classes?

**Comment by ZubAnt** [comment] 2018-10-30 09:41
I deleted the cache from the browser and it all worked!

**Comment by silentsokolov** [comment] 2018-10-30 09:44
What did you do before that? Update django 2.0 -> 2.1? switch venv?

**Comment by ZubAnt** [comment] 2018-10-30 10:01
Yes. If you use django == 2.0.9, then everything works stably. 
When using version 2.1.2, the icon is displayed only if the page is reloaded without a cache.
However, with a simple reboot, the icon is not displayed again. 
All these actions are carried out in the docker container, static files are given Nginx after the "collectstatic" command. 
If you run a project from IDEA in debug mode, then even with version 2.1.2 everything works stably.

**Comment by ZubAnt** [comment] 2018-10-30 10:53
Added class Media. It worked for me. Now, when i just reload the page the icon is always displayed

```python
class ScheduleAdmin(admin.ModelAdmin):
    list_filter = [
        ('reception_start', DateRangeFilter)
    ]

    class Media:
        js = DateRangeFilter.get_js()
```

**Comment by silentsokolov** [comment] 2018-10-30 11:09
Error in JS console?

**Comment by silentsokolov** [comment] 2018-10-30 12:12
Run with docker:

```Dockerfile
FROM python:3.6

RUN apt-get update && apt-get install -y \
        nginx \
        sqlite3 \
        gettext \
	--no-install-recommends && rm -rf /var/lib/apt/lists/*


COPY etc/nginx-app.conf /etc/nginx/sites-available/default

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

RUN python manage.py collectstatic --noinput

EXPOSE 80

CMD ["sh", "-c", "service nginx start && python manage.py runserver --nostatic"]
```

```
server {
   listen 80;
   server_name host.com;

   location / {
       try_files $uri $uri/index.html @backend;
       root /usr/src/front;
   }

   location ^~ /static/ {
       alias /usr/src/static/;
   }

   location ^~ /data/ {
       alias /usr/src/data/;
   }

   location @backend {
       proxy_pass http://localhost:8000;
       proxy_redirect off;
       proxy_set_header   Host $host;
       proxy_set_header   X-Real-IP $remote_addr;
       proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header   X-Forwarded-Host $server_name;
   }
}
```

`docker build -t foo . && docker run --name="bar" --rm -it -p 9000:80 foo`

With cache / out cache -  works (((

**Comment by ZubAnt** [comment] 2018-10-30 12:32
OK. I think the problem is somewhere in my code. but it is very strange. I solved this problem with the help of adding the Media class and I like this solution. I suggest to close the issue

**Comment by silentsokolov** [comment] 2018-10-30 12:38
[Here](https://github.com/silentsokolov/django-admin-rangefilter/issues/9) the reason why we refused this solution.

Thank. I will not close the issue, because the problem is serious, but need more information

**Comment by silentsokolov** [comment] 2018-10-30 12:44
@ZubAnt please, 
```
$(".datetimeshortcuts").remove();
DateTimeShortcuts.init();
```
If possible, paste the following code into [104-105 lines](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/templates/rangefilter/date_filter.html#L105)

**Comment by ZubAnt** [comment] 2018-10-30 13:06
i am install from here https://github.com/ZubAnt/django-admin-rangefilter/commit/99a46070ed5e9b333353d55af55f7955c77add7c

```
Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> ((index):277)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
```

<img width="531" alt="2018-10-30 16 04 33" src="https://user-images.githubusercontent.com/19777376/47719922-ac903000-dc5d-11e8-87fc-37673d845010.png">

**Comment by silentsokolov** [comment] 2018-10-30 13:13
Ok, big thx!

**Comment by silentsokolov** [comment] 2018-10-30 13:56
Oh, i know is code not best, this can help.

Replace block [here](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/templates/rangefilter/date_filter.html#L98) to:

```javascript
   django.jQuery('document').ready(function () {
        if (!('DateTimeShortcuts' in window)) {
            django.jQuery.when(
                {% for m in spec.form.js %}
                    django.jQuery.getScript('{{m}}'),
                {% endfor %}
                django.jQuery.Deferred(function( deferred ){
                    django.jQuery( deferred.resolve );
                })
            ).done(function(){
                django.jQuery(".datetimeshortcuts").remove();
                DateTimeShortcuts.init();
            });
        }
    });
```

If you encounter the same problem please comment here

**Comment by ZubAnt** [comment] 2018-10-30 15:14
It work with/out cache! https://github.com/ZubAnt/django-admin-rangefilter/commit/4b48c94c7e2b2c6675b3e364cfb87e2a70c36379

**Closed** 2018-10-31 09:37 UTC
Labels: help wanted

**Comment by qulc** [comment] 2018-12-12 06:21
is not resolved. 

 `calendar.js` `DateTimeShortcuts.js` is not loaded.

![image](https://user-images.githubusercontent.com/4693764/49850539-d28e2000-fe18-11e8-9397-e9e058f3b645.png)

**Comment by silentsokolov** [comment] 2018-12-12 07:40
Please, show `admin.py`. You use default `admin.ModelAdmin` without overrides?

**Comment by qulc** [comment] 2018-12-12 09:52
I overrides  `change_list` method in `admin.ModelAdmin`

Now without overrides is worked.

**Comment by denisvolokh** [comment] 2019-01-07 05:13
Hi,

I have the same problem with the overriding change_list template. 

If I override change_list template date range component stop working and here is the error from console:

![image](https://user-images.githubusercontent.com/261410/50750079-ee50de80-127d-11e9-844d-ff429d1530f8.png)

**Comment by silentsokolov** [comment] 2019-01-07 07:52
try reimport jQuery.js

**Comment by denisvolokh** [comment] 2019-01-07 08:40
Did not work. Here is my template: 

{% extends "admin/change_list.html" %}

{% load staticfiles %}

{% block extrahead %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>

    <script>
        window.onload = function () {
            console.log("[+] Window onLoad!")

            Highcharts.chart("chart", {{chart|safe}});
        }
    </script>
{% endblock %}

{% block content %}
    <div id="chart" >Additional content goes here</div>
    {{ block.super }}
{% endblock %}

**Comment by silentsokolov** [comment] 2019-01-07 09:09
`jQuery` != `django.query`, try import [init.js](https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/jquery.init.js)

**Comment by denisvolokh** [comment] 2019-01-07 09:54
Tried to load jquery and jquery.ini like:

{% block extrahead %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>

    <script src="https://code.highcharts.com/highcharts.src.js"></script>

    <script>
        window.onload = function () {
            console.log("[+] Window onLoad!")

            Highcharts.chart("chart", {{chart|safe}});
        }
    </script>
{% endblock %}

Now getting this error:

![image](https://user-images.githubusercontent.com/261410/50761365-2cadc400-12a5-11e9-850d-3219385ddbbb.png)

**Comment by VictorIsra** [comment] 2020-07-12 01:00
Django==2.2.12
django-admin-rangefilter==0.6.1

admin.py:
`
from rangefilter.filter import DateRangeFilter, DateTimeRangeFilter
from .models import Event

@admin.register(Event)
class EventAdmin(admin.ModelAdmin):
    list_filter = (
        ('date', DateRangeFilter), ('date', DateTimeRangeFilter),
    )
    `
![errorr](https://user-images.githubusercontent.com/22859643/87236583-9e4a5f00-c3c1-11ea-8642-c897fd138a7c.png)

**Comment by silentsokolov** [comment] 2020-07-12 04:57
@VictorIsra
Hello, Grapelli != Django. We dont support it.

**Comment by VictorIsra** [comment] 2020-07-12 11:30
Hello! oh, too bad. Do you have any perspective of adding Grapelli support?
this project is pretty similar and works on Grapelli, but it has an unusual alphabet:

[](https://pypi.org/project/django-admin-rangefilter-jalali/)

**Comment by silentsokolov** [comment] 2020-07-12 14:23
> Hello! oh, too bad. Do you have any perspective of adding Grapelli support?

I dont think so. ... 

PR welcome!
